services:
  - type: web
    name: irriguide-advisor
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_KEY
        sync: false
